name: Publish to Telegram

# Разрешаем запуск ручной / API
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to publish'
        required: true
        type: string
      image_url:
        description: 'URL of image'
        required: false
        type: string
  repository_dispatch:
    types: [publish_from_n8n]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  # Обновлено до v4 для актуальности и безопасности

    - name: Setup Python
      uses: actions/setup-python@v5  # Обновлено до v5 для поддержки новых фич и фиксов
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install telethon aiohttp pillow python-magic
    - name: Run publish script
      env:
        API_ID: ${{ secrets.TELEGRAM_API_ID }}
        API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        PUBLISH_TEXT: ${{ github.event.inputs.text || github.event.client_payload.text }}  # Поддержка для workflow_dispatch и repository_dispatch
        PICTURE_URL: ${{ github.event.inputs.image_url || github.event.client_payload.image_url }}  # Поддержка для workflow_dispatch и repository_dispatch
      run: python publish.py
