name: Publish to Telegram

# Разрешаем запуск ручной / API
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to publish'
        required: true
        type: string
      image_url:
        description: 'URL of image'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install telethon

    - name: Run publish script
      env:
        API_ID: ${{ secrets.TELEGRAM_API_ID }}
        API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        PUBLISH_TEXT: ${{ github.event.inputs.text }}
        PICTURE_URL: ${{ github.event.inputs.image_url }}
      run: python publish.py
